### PR TITLE
Move blog posts to documentation

### LINKED ISSUE #143: Merge "Blog" into "Documentation: Other"
As discussed at the workshop.
The blog section has become unused and the two sections actually contain very similar types of article, they would probably be better as a combined list.

### PR DESCRIPTION
**Pull request by jrha**
Resolves #143

### CODE REVIEW

**Comment by stdweird** [comment]
post_url?
(unverified sed :smile: )
```bash
cd _posts
sed -i 's#(/documentation/\([0-9]\+\)/\([0-9]\+\)/\([0-9]\+\)/\(.*\).html#{% post_url \1-\2-\3-\4 %}#' 2*md
```

**Comment by stdweird** [comment]
also merge is greyed out for me

**Comment by jrha** [comment]
sed :scream:

**Comment by jrha** [comment]
Maybe I'll run your `sed` magic against everything in a fresh branch.

**Comment by jrha** [comment]
@jouvin, what colour is the merge button for you?

**Comment by jrha** [comment]
Interestingly it's grey for me too now.

**Comment by jrha** [comment]
All :green_apple:'s now

**Pull request merged**
