### PR TITLE
aquilon: Link to tagged version of gerrit hook

### PR DESCRIPTION
**Pull request by jrha**
More consistent. Plus it seems to have disappeared from master.

### CODE REVIEW

**Comment by stdweird** [comment]
see #224

**Comment by stdweird** [comment]
@jrha still spellchecker errors

**Comment by jrha** [comment]
Well yes, because this isn't based on that branch.

**Comment by jrha** [comment]
@stdweird rebased on master…

**Comment by jrha** [comment]
Don't merge until last commit is replaced with a reference to a tagged release of stfc/markdown-spellchecker.

**Pull request merged**
