### PR TITLE
add a link to the 17.2.0 documentation

### PR DESCRIPTION
**Pull request by wdpypere**

### CODE REVIEW

**Comment by wdpypere** [comment]
fails on http://lapp.in2p3.fr/Quattor

**Comment by jouvin** [comment]
Every reference to this URL is missing. In fact there is a commit to fix it in PR #201. You may want to fetch the source branch of this PR and cherry-pick the corresponding commit...

**Comment by ned21** [comment]
Cherry-picking cef9dc40c7bf17335cf66d60601e57ef51b16379 from #201 will mean that branch will need to get rebased and the duplicate commit removed but if that PR is not near being ready to go then it makes sense so we can have clean tests to merge this.

**Comment by wdpypere** [comment]
@jouvin fixed

**Pull request merged**
