### PR TITLE
Fix September 2007 workshop notes

### PR DESCRIPTION
**Pull request by jrha**

### CODE REVIEW

**Comment by ned21** [comment]
Also - are we worried about this?

```
- ./_site/development/00-basics.html
1082  *  External link https://jenkins0.ugent.be/ failed: got a time out (response code 0)
1083htmlproofer 3.14.1 | Error:  HTML-Proofer found 1 failure!
```

**Comment by jrha** [comment]
Thanks, I'll add a commit to fix up the spelling shortly.

**Comment by jrha** [comment]
@ned21 I'm not worried about the dead Jenkins link in the context of this PR.
In general though, yes it would be nice if it was reachable.

**Comment by jrha** [comment]
Spellchecker now passes, Jenkins link is still dead, but not from these notes.

**Pull request merged**
