### PR TITLE
Fix broken references, configuration messes and more

### PR DESCRIPTION
**Pull request by jrha**
Should allow travis tests to pass!

### CODE REVIEW

**Comment by ned21** [comment]
:+1:

**Comment by stdweird** [comment]
:open_mouth:

**Comment by jrha** [comment]
Or not...

**Comment by jrha** [comment]
That's more like it.

**Comment by stdweird** [comment]
waiting for anything else or can we merge this? (like scripts that generate the links/docs?)

**Comment by jrha** [comment]
Should be good to go

**Comment by jrha** [comment]
I fixed the links manually, the auto-generated component docs are legacy stuff now anyway.

**Pull request merged**
