### PR TITLE
Cleanup textrender posts and add metaconfig convert option

### PR DESCRIPTION
**Pull request by stdweird**

### CODE REVIEW

**Comment by stdweird** [comment]
@jrha fixed typo and previous travis failure. now fails with missing link from updated read-the-docs
@wdpypere can you push a new version of the readthedocs documentation?

**Comment by wdpypere** [comment]
@stdweird I'll have a look tomorrow to upload a new version.

**Comment by wdpypere** [comment]
@stdweird updated at http://docs-test-comps.readthedocs.org/en/latest/

**Comment by wdpypere** [comment]
wrong button, sorry.

**Comment by stdweird** [comment]
@wdpypere thx for building and retriggering the tests

**Pull request merged**
