### PR TITLE
Generate the current year when pages are rebuilt

### PR DESCRIPTION
**Pull request by jrha**
This way no-one has to remember to update the copyright message each year.

### CODE REVIEW

**Comment by stdweird** [comment]
@jrha needs a rebase

**Comment by jrha** [comment]
Does it?

**Comment by stdweird** [comment]
@jrha well the merge button is greyed out, so if you want someone to merge it ...

**Comment by jrha** [comment]
Funny, it's not greyed out for me...

**Comment by stdweird** [comment]
i get 
```
This branch is out-of-date with the base branch
Merge the latest changes from master into this branch. 
```

**Comment by jrha** [comment]
Well I blame GitHub.

**Pull request merged**
