### PR TITLE
Aquilon documentation update

### PR DESCRIPTION
**Pull request by jouvin**
- Installation guide replaced by a reference to Aquilon `README.md` file (until the README content is moved back to the web site...)
- Configuration steps updated/clarified based on March 17 workshop hands-on session

### CODE REVIEW

**Comment by ned21** [comment]
Does this have a dependency on an update to the README.md in the Aquilon repo?

**Comment by jouvin** [comment]
@jrha it is not strictly a dependency but https://github.com/quattor/aquilon/pull/36 and this PR work together. After merging everything, I think we should move Aquilon `README.md` in the installation page on the web site and put a reference to it in the README. In the meantime I updated the installation page to refer to it to avoid a circular dependency. But if https://github.com/quattor/aquilon/pull/36 is merged before we merge this PR, we may move its content in the installation page as part of this PR (and to the companion update in Aquilon).

**Comment by jouvin** [comment]
https://github.com/quattor/aquilon/pull/36 has been merged. If there is no other remarks, I suggest merging this one too.

**Comment by jouvin** [comment]
This PR will probably conflict with #212... A rebase should allow to fix things easily depending on which one is merged first...

**Comment by jouvin** [comment]
After discussion in https://github.com/quattor/aquilon/pull/56, installation guide has been replaced by Aquilon README.md contents from https://github.com/quattor/aquilon/pull/36, following https://github.com/quattor/aquilon/issues/57 suggestion.

**Comment by jrha** [comment]
This needs rebasing now that #207 is merged.

**Comment by jouvin** [comment]
Rebased done.

**Comment by jouvin** [comment]
The test is failing because it seems that there was some changes at CERN regarding Twiki access (Twiki being reference in some of our old pages). I just opened https://cern.service-now.com/service-portal/view-request.do?n=RQF0730725 at CERN support to understand if it is intentional/permanent. Merging #213 would help to work around this problem...

**Comment by jouvin** [comment]
Problem with CERN Twiki disappeared, not sure what happened exactly. According to CERN, nothing changed. Should be ok now and ready for merging.

**Pull request merged**
