### PR TITLE
Grenoble summary: fix formatting errors

### PR DESCRIPTION
**Pull request by jouvin**
We missed during the original review that the text was not displayed properly on Jekyll due to missing blank lines...

### CODE REVIEW

**Comment by stdweird** [comment]
@jouvin i looked at
https://github.com/jouvin/quattor.github.com/blob/grenoble-workshop/_posts/2015-03-03-grenoble-workshop-
summary.md
which seems ok. how can we have a preview of the html?

**Comment by jouvin** [comment]
You need a local Jekyll installation... I don't know of any other mean to validate a MD file displayed by Jekyll. May be @jrha has such an installation and can validate that it displays properly (I did it this time!).

**Comment by jrha** [comment]
Goto "Files changed" tab and press the "view" button.

**Comment by jrha** [comment]
But I suspect there may be differences between GitHub's parsing of markdown and whatever Jekyll is using.

**Comment by jouvin** [comment]
@jrha yes, GH's parsing is not enough to identify these problems as it is much more permissive regarding the need of blank lines than Jekyll... If nobody is able to double check, I suggest that you merge this PR (I checked it and it's always a huge improvement in term of readibility).

**Comment by jrha** [comment]
Much better!

**Pull request merged**
