### PR TITLE
contacts: add freenode channel

### PR DESCRIPTION
**Pull request by stdweird**

### CODE REVIEW

**Comment by jouvin** [comment]
Are you (or somebody else) regurlarly connected on IRC? If we say it, we need to ensure that the channel is not left empty!

About the check failure, I've seen it yesterday in another context. I have the feeling that this is caused by sites who refuse robots. May be htmlproofer can be tuned to say that it is not a robot (as we want to assess access for humans).

**Comment by stdweird** [comment]
the channel is in my autoconnect list

wrt the error, it looks like desy is blocking travis, because if i run the htmlproofer from my laptop, all is fine.

**Comment by stdweird** [comment]
@jouvin i sortof fixed it by ignore the desy indico url. i'm aware that his is not a proper fix, yet see no other real option right away

**Comment by jouvin** [comment]
The other alternative that I used in another context is to convert the URL to text in the post... Makes it still present... In my view this is probably better than an exception to htmlproofer...

**Comment by stdweird** [comment]
but there's nothing wrong with the url or the way it is used in the document. i'd rather ignore it in the test than change it (who knows, maybe sometime in the future it works again).

**Comment by jouvin** [comment]
The point is that it is not reliable. This is why I suggest converting it ot a text (not processed by htmlproofer) rather than putting an exception...

**Comment by stdweird** [comment]
what is not reliable?

**Comment by jouvin** [comment]
DESY indico as it works sometimes but not always...

**Comment by stdweird** [comment]
it seems to always work for me locally, but i think they blacklist travis, not the whole world.

**Comment by jrha** [comment]
I'd prefer it to remain a link and to add exceptions to the tests rather than breaking functionality on our website.

**Pull request merged**
